### ISSUE TITLE
async, await can totally replace Coroutine?

### ISSUE THREAD

**Issue by fqchenzhen** [Ellpeck/Coroutine#16]
I tried async await running on different threads？

**Comment by Ellpeck** [comment]
Yes, you can use async actions for a similar experience using multiple threads!

Part of the point of Coroutine is that it *doesn't* use multiple threads, meaning you can do anything in a coroutine you would normally do on the main thread only.

> No multi-threading, which allows for any kind of process to be executed in a coroutine, including rendering

There's also ways of using the async/await API to achieve something similar all in one thread, but when designing Coroutine, we went with the enumerable system since it makes it much clearer that it's all happening on the same thread.
