### ISSUE TITLE
CoroutineHandlerInstance.GetEventCoroutines can return null 

### ISSUE THREAD

**Issue by Shadowblitz16** [Ellpeck/Coroutine#19]
CoroutineHandlerInstance.GetEventCoroutines can return null causing problems down the line.

Consider turning on strict nullable checking to see the warnings or errors

**Comment by Ellpeck** [comment]
`GetEventCoroutines` is a private method that is designed to be able to return null. Coroutine doesn't (yet) use nullable reference types, which is why there aren't any additional annotations or anything to signify this. 

Feel free to report an issue if you run into any crashes related to this, of course!
